name: yahoo_fantasy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - ipython
  - ipykernel
  - tqdm
  - pyaml
  - pytest
  - pip
  - pip:
    - nba_api
    - yahoo-fantasy-api
    - yahoo-oauth
    - dataframe-image

